module.exports = {
    '$root': '/',
    '$app': '/app',
    '$data': '/data',
    '$config': '/config',
    '$bootstrapers': '/bootstrapers',
    '$database': '/database',
    '$migrations': '/database/migrations',
    '$seeders': '/database/seeders',
    '$storage': '/storage',
    '$errors': '/app/errors',
    '$controllers': '/app/http/controllers',
    '$middlewares': '/app/http/middlewares',
    '$requests': '/app/http/requests',
    '$models': '/app/models',
    '$resources': '/app/resources',
    '$routes': '/app/routes',
    '$utils': '/app/utils',
    '$services': '/app/services',
    '$rules' : '/app/rules'
};